on:
  push:
    branches:
      - main

jobs:
  deployEKS:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        id: init 
        run: terraform init --upgrade

      - name: Terraform Apply
        id: deploy
        run: terraform apply --auto-approve
        continue-on-error: true


        
        env:
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_KEY }}

      # - name: Terraform Validate
      #   uses: hashicorp/terraform-github-actions/validate@v0.3.7
      #   env:
      #     AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY }}
      #     AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_KEY }}

